# Generated by Django 3.0.5 on 2020-04-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_item_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_part',
            old_name='part_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item_part',
            old_name='part_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='item_part',
            old_name='part_number',
            new_name='number',
        ),
    ]
