# Generated by Django 3.0.5 on 2020-04-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_auto_20200412_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_part',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_part', to='part.Item'),
        ),
    ]
